services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=startup_scout
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your-secret-key-change-in-production
      - LOG_LEVEL=debug
      - STORAGE_TYPE=local
      - STORAGE_LOCAL_PATH=/app/uploads
      - STORAGE_MAX_FILE_SIZE=10485760
      - STORAGE_BASE_URL=http://localhost:8080/images
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      - postgres
      - redis
    networks:
      - startup-scout-network

  postgres:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=startup_scout
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
      - ./backend/testdata:/testdata
    networks:
      - startup-scout-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - startup-scout-network

volumes:
  postgres_data:
  redis_data:
  uploads_data:

networks:
  startup-scout-network:
    driver: bridge 