services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    networks:
      - startup-scout-network

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
      network: host
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./env.development
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      - postgres
    networks:
      - startup-scout-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      network: host
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - app
    networks:
      - startup-scout-network

  postgres:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
      - POSTGRES_DB=${DB_NAME:-startup_scout}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    networks:
      - startup-scout-network


volumes:
  postgres_data:
ÑŒ  uploads_data:

networks:
  startup-scout-network:
    driver: bridge