server:
  port: "8080"
  read_timeout: "30s"
  write_timeout: "30s"

database:
  host: ""
  port: "5432"
  user: "postgres"
  password: "password"
  dbname: "startup_scout"
  sslmode: "disable"

auth:
  telegram_bot_token: ""
  jwt_secret: ""
  session_duration: "24h"

logger:
  level: "info"

storage:
  type: "local"
  local_path: "./uploads"
  max_file_size: 10485760  # 10MB
  allowed_types: ["image/jpeg", "image/png", "image/gif", "image/webp"]
  base_url: "http://localhost:8080/images"
